### ISSUE TITLE
Regular answer of name to uci command

### ISSUE THREAD

**Issue by olithink** [mattbruv/Quokka#3]
Hello, thank you for your nice and usefull engine.
Unfortunately there is a little protocol bug, the answer to the "uci" command is:

`
id Quokka 2.1
`

while it is supposed to be

`
id name Quokka 2.1
`
This is important for tournaments in order to identify the engine correctly.

**Comment by mattbruv** [comment]
Thanks!

**Comment by olithink** [comment]
Thank you! Together with the -lpthread flag in Makefile Quokka will be added to a "bugfree *nix engine list"
