### ISSUE TITLE
Cannot compile Quokka 2.1: undefined reference to pthread_create

### ISSUE THREAD

**Issue by rchastain** [mattbruv/Quokka#4]
Hello!

I am on Linux. When I type `make`, I get this:

```
[roland@localhost quokka (master)]$ LC_ALL=c make
g++ -O2 -Wall -std=c++11 -c src/attack.cpp -o obj/attack.o
g++ -O2 -Wall -std=c++11 -c src/search.cpp -o obj/search.o
g++ -O2 -Wall -std=c++11 -c src/uci.cpp -o obj/uci.o
g++ -O2 -Wall -std=c++11 -c src/evaluate.cpp -o obj/evaluate.o
g++ -O2 -Wall -std=c++11 -c src/position.cpp -o obj/position.o
g++ -O2 -Wall -std=c++11 -c src/perft.cpp -o obj/perft.o
g++ -O2 -Wall -std=c++11 -c src/movegen.cpp -o obj/movegen.o
g++ -O2 -Wall -std=c++11 -c src/main.cpp -o obj/main.o
g++ -O2 -o quokka obj/attack.o obj/search.o obj/uci.o obj/evaluate.o obj/position.o obj/perft.o obj/movegen.o obj/main.o
/usr/bin/ld: obj/uci.o: in function `go(std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >&)':
uci.cpp:(.text+0x9d5): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make: *** [Makefile:9: quokka] Error 1
[roland@localhost quokka (master)]$ 
```
With Quokka 2.0, I don't have this problem.

Would you know where it comes from?

Best regards.

Roland

**Comment by mattbruv** [comment]
It looks like you may have to include a compiler flag or something? https://www.google.com/search?q=undefined+reference+to+%60pthread_create%27&oq=undefined+reference+to+%60pthread_create%27&aqs=chrome..69i57&sourceid=chrome&ie=UTF-8

**Comment by rchastain** [comment]
OK, I finally found the solution. I made the following modification in the _Makefile:_

```
quokka: $(OBJ_FILES)
#	   g++ -O2 -o $@ $^
	   g++ -O2 -o $@ $^ -lpthread

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
#	   g++ -O2 $(CXXFLAGS) -c $< -o $@
	   g++ -O2 $(CXXFLAGS) -c $< -o $@ -lpthread
```

**Comment by mattbruv** [comment]
Thanks for taking interest in my engine, and helping me solve this problem for building on linux

https://github.com/mattbruv/Quokka/commit/a3d048a85813fd787af41f28914b4931e8688b20

**Comment by olithink** [comment]
Thank you for the -lpthread flag (important for Linux).
There is still a very small issue with "make". One has to create an "obj" directory, if not, this error happens:
```
make
g++ -O2 -Wall -std=c++11 -c src/attack.cpp -o obj/attack.o -lpthread
Assembler messages:
Fatal error: can't create obj/attack.o: No such file or directory
make: *** [Makefile:12: obj/attack.o] Error 1
```

**Comment by rchastain** [comment]
> There is still a very small issue with "make". One has to create an "obj" directory, if not, this error happens:
> 

I tried the following modification. It seems to work.

```
CXXFLAGS := -Wall -std=c++11

all: directory quokka

directory:
	mkdir -p obj

quokka: $(OBJ_FILES)
```
